export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  JOBS: '/jobs',
  JOB_CREATE: '/jobs/create',
  JOB_DETAILS: '/jobs/:id',
  JOB_EDIT: '/jobs/:id/edit',
  CV_UPLOAD: '/jobs/:id/upload',
  CANDIDATES: '/candidates',
  CANDIDATE_DETAILS: '/candidates/:id',
  REPORTS: '/reports',
  ADMIN_USERS: '/admin/users',
  ADMIN_API_CONFIG: '/admin/api-config',
  ADMIN_SYSTEM_STATUS: '/admin/system-status',
  ADMIN_DATABASE_STATUS: '/admin/database-status',
};
